Exercise.create(title: "Arm Flexion", body: "This is how you do this exercise.")
Exercise.create(title: "Arm Extension", body: "This is how you do this exercise.")
Exercise.create(title: "Hip Flexion", body: "This is how you do this exercise.")
Exercise.create(title: "Hip Extension", body: "This is how you do this exercise.")
Exercise.create(title: "Knee Flexion", body: "This is how you do this exercise.")
Exercise.create(title: "Knee Extension", body: "This is how you do this exercise.")
Exercise.create(title: "Shoulder Flexion", body: "This is how you do this exercise.")
Exercise.create(title: "Shoulder Extension", body: "This is how you do this exercise.")